### ISSUE TITLE
What is the requirements for Woocommerce site?

### ISSUE THREAD

**Issue by r0n22** [g4m3r0/LicenseManager-for-WooCommerce-.Net-Library#11]
Is there any requirements for the Woo Commerce instance?  

Any required plugins or a vanilla instance would work?

**Comment by g4m3r0** [comment]
Yes, the Licensemanager for WooCommerce plugin is required. It is available for free in the WordPress plugin store: https://wordpress.org/plugins/license-manager-for-woocommerce/ .
